export const INITIAL_USERS = [
  {
    id: 'u1',
    name: 'Admin User',
    email: 'admin@farming.com',
    role: 'admin',
  },
  {
    id: 'u2',
    name: 'John Farmer',
    email: 'farmer@farming.com',
    role: 'farmer',
    category: 'agriculture',
    mobile: '1234567890',
    state: 'California',
    city: 'Fresno'
  },
  {
    id: 'u3',
    name: 'Acme Buyer',
    email: 'buyer@farming.com',
    role: 'buyer',
    mobile: '0987654321',
    state: 'New York',
    city: 'NYC'
  }
];

export let resetTokens = [];

export const INITIAL_CHATS = [
  {
    id: 'chat_1',
    name: 'Fresh Foods Co.',
    avatar: 'https://ui-avatars.com/api/?name=Fresh+Foods&background=0D8ABC&color=fff',
    lastMessage: 'Is the price negotiable?',
    time: '10:30 AM',
    unread: 2,
  },
  {
    id: 'chat_2',
    name: 'Green Valley Dairy',
    avatar: 'https://ui-avatars.com/api/?name=Green+Valley&background=2D6A4F&color=fff',
    lastMessage: 'We will dispatch the truck tomorrow morning.',
    time: 'Yesterday',
    unread: 0,
  }
];

export const INITIAL_CONTRACTS = [
  // --- AGRICULTURE ---
  {
    id: 'c1',
    buyerName: 'Fresh Foods Co.',
    buyerRating: 4.8,
    category: 'agriculture',
    product: 'Organic Tomatoes',
    productImage: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=800',
    quantity: '500 kg',
    quality: 'Grade A',
    price: '₹2.50/kg',
    totalPrice: '₹1,250',
    timeline: 'Oct 15 - Nov 30',
    deliveryLocation: 'Central Market, Delhi',
    distance: '45 km',
    transportIncluded: false,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'c4',
    buyerName: 'Agro Exports Ltd.',
    buyerRating: 4.7,
    category: 'agriculture',
    product: 'Basmati Rice',
    productImage: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800',
    quantity: '5000 kg',
    quality: 'Export Grade',
    price: '₹45/kg',
    totalPrice: '₹2,25,000',
    timeline: 'Nov 1 - Dec 31',
    deliveryLocation: 'APMC Yard, Mumbai',
    distance: '120 km',
    transportIncluded: true,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'c5',
    buyerName: 'SpiceRoute Traders',
    buyerRating: 4.5,
    category: 'agriculture',
    product: 'Red Onions',
    productImage: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&q=80&w=800',
    quantity: '2000 kg',
    quality: 'Grade B',
    price: '₹18/kg',
    totalPrice: '₹36,000',
    timeline: 'Oct 20 - Nov 15',
    deliveryLocation: 'Lasalgaon Market, Nashik',
    distance: '30 km',
    transportIncluded: false,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },

  // --- DAIRY ---
  {
    id: 'c2',
    buyerName: 'Green Valley Dairy',
    buyerRating: 4.9,
    category: 'dairy',
    product: 'Fresh Full-Cream Milk',
    productImage: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
    quantity: '1000 L/week',
    quality: 'Premium A2',
    price: '₹55/L',
    totalPrice: '₹2,20,000/mo',
    timeline: 'Ongoing',
    deliveryLocation: 'Processing Plant, Pune',
    distance: '12 km',
    transportIncluded: true,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'c6',
    buyerName: 'Amul Partner',
    buyerRating: 5.0,
    category: 'dairy',
    product: 'Buffalo Milk',
    productImage: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&q=80&w=800',
    quantity: '500 L/day',
    quality: 'High Fat Grade',
    price: '₹60/L',
    totalPrice: '₹90,000/mo',
    timeline: 'Nov - Mar',
    deliveryLocation: 'Amul Chilling Centre, Anand',
    distance: '22 km',
    transportIncluded: true,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'c7',
    buyerName: 'MilkBasket Co.',
    buyerRating: 4.4,
    category: 'dairy',
    product: 'Paneer (Cottage Cheese)',
    productImage: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&q=80&w=800',
    quantity: '200 kg/week',
    quality: 'Fresh Grade A',
    price: '₹280/kg',
    totalPrice: '₹56,000/mo',
    timeline: 'Ongoing',
    deliveryLocation: 'Cold Storage Hub, Bengaluru',
    distance: '18 km',
    transportIncluded: false,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },

  // --- AQUACULTURE ---
  {
    id: 'c3',
    buyerName: 'Ocean Catch Inc.',
    buyerRating: 4.6,
    category: 'aquaculture',
    product: 'Atlantic Salmon',
    productImage: 'https://images.unsplash.com/photo-1574781330855-d0db8cc6a79c?auto=format&fit=crop&q=80&w=800',
    quantity: '2000 kg',
    quality: 'Export Grade',
    price: '₹680/kg',
    totalPrice: '₹13,60,000',
    timeline: 'Dec 1 - Dec 15',
    deliveryLocation: 'Port Authority, Chennai',
    distance: '85 km',
    transportIncluded: false,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'c8',
    buyerName: 'SeaFresh Exports',
    buyerRating: 4.8,
    category: 'aquaculture',
    product: 'Tiger Shrimp',
    productImage: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&q=80&w=800',
    quantity: '1500 kg',
    quality: 'Premium Export',
    price: '₹550/kg',
    totalPrice: '₹8,25,000',
    timeline: 'Nov 10 - Nov 30',
    deliveryLocation: 'Seafood Park, Vizag',
    distance: '40 km',
    transportIncluded: true,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'c9',
    buyerName: 'Freshwater Foods',
    buyerRating: 4.3,
    category: 'aquaculture',
    product: 'Rohu Fish',
    productImage: 'https://images.unsplash.com/photo-1524704654690-b56c05c78a00?auto=format&fit=crop&q=80&w=800',
    quantity: '800 kg',
    quality: 'Grade A Fresh',
    price: '₹120/kg',
    totalPrice: '₹96,000',
    timeline: 'Oct 25 - Nov 10',
    deliveryLocation: 'Fish Market, Kolkata',
    distance: '55 km',
    transportIncluded: false,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },

  // --- POULTRY ---
  {
    id: 'c10',
    buyerName: 'EggMart Retail Chain',
    buyerRating: 4.7,
    category: 'poultry',
    product: 'Farm Fresh Eggs',
    productImage: 'https://images.unsplash.com/photo-1587486913049-53fc88980cfc?auto=format&fit=crop&q=80&w=800',
    quantity: '10,000 eggs/week',
    quality: 'Grade A Large',
    price: '₹7/egg',
    totalPrice: '₹2,80,000/mo',
    timeline: 'Ongoing',
    deliveryLocation: 'Distribution Hub, Hyderabad',
    distance: '25 km',
    transportIncluded: true,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'c11',
    buyerName: 'Licious Foods',
    buyerRating: 4.9,
    category: 'poultry',
    product: 'Broiler Chicken',
    productImage: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&q=80&w=800',
    quantity: '500 kg/week',
    quality: 'Fresh Dressed',
    price: '₹180/kg',
    totalPrice: '₹3,60,000/mo',
    timeline: 'Nov 1 onwards',
    deliveryLocation: 'Processing Unit, Chennai',
    distance: '35 km',
    transportIncluded: false,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'c12',
    buyerName: 'Country Delight',
    buyerRating: 4.6,
    category: 'poultry',
    product: 'Country Eggs (Naatu Muttai)',
    productImage: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&q=80&w=800',
    quantity: '5000 eggs/week',
    quality: 'Free Range Organic',
    price: '₹12/egg',
    totalPrice: '₹2,40,000/mo',
    timeline: 'Ongoing',
    deliveryLocation: 'Organic Hub, Coimbatore',
    distance: '15 km',
    transportIncluded: true,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
];
