// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwSRwfvUuKysA33YkuIFIckN0HiR2g_4k',
    appId: '1:64549952068:web:e3d3db330ccdb098167a11',
    messagingSenderId: '64549952068',
    projectId: 'smart-agri-1112a',
    authDomain: 'smart-agri-1112a.firebaseapp.com',
    storageBucket: 'smart-agri-1112a.firebasestorage.app',
    measurementId: 'G-N8RNGENPY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV5AYqawjhYjJWJqOt7isAz4CqXwdJcTI',
    appId: '1:64549952068:android:e3361d820bd696b5167a11',
    messagingSenderId: '64549952068',
    projectId: 'smart-agri-1112a',
    storageBucket: 'smart-agri-1112a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBltAWuu5YULxIElJuBXluEBKixUPM4cdU',
    appId: '1:64549952068:ios:bb29ffee79909145167a11',
    messagingSenderId: '64549952068',
    projectId: 'smart-agri-1112a',
    storageBucket: 'smart-agri-1112a.firebasestorage.app',
    iosBundleId: 'com.example.smartAgriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBltAWuu5YULxIElJuBXluEBKixUPM4cdU',
    appId: '1:64549952068:ios:bb29ffee79909145167a11',
    messagingSenderId: '64549952068',
    projectId: 'smart-agri-1112a',
    storageBucket: 'smart-agri-1112a.firebasestorage.app',
    iosBundleId: 'com.example.smartAgriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwSRwfvUuKysA33YkuIFIckN0HiR2g_4k',
    appId: '1:64549952068:web:015ebf5de0c7ff59167a11',
    messagingSenderId: '64549952068',
    projectId: 'smart-agri-1112a',
    authDomain: 'smart-agri-1112a.firebaseapp.com',
    storageBucket: 'smart-agri-1112a.firebasestorage.app',
    measurementId: 'G-MF12VHQ2TC',
  );
}
